name: .NET

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  build:
    uses: demo-canarys/template-repo/.github/workflows/main.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build }
